#!/bin/bash

# if [ $# -ne 1 ]; then
#     echo "usage: ./copy-to  file_extension [ destinaton_folder ]"
#     exit 1
# fi

# Extension of files to copy.
FILE_EXTENSION=${1:-go}

# Destination folder.
DEST_FOLDER=${1:-pkg}

get-files() {
	# Non-recursive file search
	find . -name "$1" -print0
}

copy-files() {
	# Copy files to destination folder.
	# This is a non-recursive function.
	#   - First argument should be pattern to match.
	#   - Second argument is folder path.
	find . -name "$1" -print0 | xargs -0 cp -t "$2"
}

edit-files() {
	# Example usage:
	# 	find . -path "./${DEST_FOLDER}/*.go" -print0 | edit-files

	# Note: `-i` option means in-place edit.

	while IFS= read -r -d $'\0' arg; do
		sed -i 's/package main/package pkg/' "$arg"
	done
}

copy-files "*.${FILE_EXTENSION}" "${DEST_FOLDER}" && find . -path "./${DEST_FOLDER}/*.go" -print0 | edit-files

# find . -path "./${DEST_FOLDER}/*.go" -print0 | edit-files
# get-files "*.${FILE_EXTENSION}"